AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    event-tracker

    Sample SAM Template for event-tracker

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3

Resources:
    EventTrackerFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: event-tracker/dist
            Handler: app.lambdaHandler
            Runtime: nodejs14.x
            Architectures:
                - x86_64
            Events:
                TrackEvents:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /track-event
                        Method: post

Outputs:
    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    TrackEventsApi:
        Description: 'API Gateway endpoint URL for Prod stage for Track Events function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/track-event/'
    EventTrackerFunction:
        Description: 'Track Events Lambda Function ARN'
        Value: !GetAtt EventTrackerFunction.Arn
    EventTrackerFunctionIamRole:
        Description: 'Implicit IAM Role created for Event Tracker function'
        Value: !GetAtt EventTrackerFunctionRole.Arn
